tasks:
  horriblesubs:
    rss: https://nyaa.si/rss?u=HorribleSubs
    series:
      1080p:
        - Tsurune
        - Beelzebub\-jou no Okinimesu mama
        - Toaru Majutsu no Index
        - Karakuri Circus
        - Merc Storia \- Mukiryoku Shounen to Bin no Naka no Shoujo
        - Conception
        - Anima Yell
        - Ulysses \- Jeanne d'Arc to Renkin no Kishi
        - Release the Spyce
        - SSSS\.Gridman
        - Sword Art Online \- Alicization
        - Goblin Slayer
        - Irozuku Sekai no Ashita kara
        - Kishuku Gakkou no Juliet
        - Uchi no Maid ga Uzasugiru
        - Hinomaru Sumo
        - Yagate Kimi ni Naru
        - Tonari no Kyuuketsuki\-san
        - Zombieland Saga
        - Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai
        - Sora to Umi no Aida
        - Kaze ga Tsuyoku Fuiteiru
        - Akanesasu Shoujo
        - Tensei Shitara Slime Datta Ken
        - Yakusoku no Nanaya Matsuri
        - Yuragi\-sou no Yuuna\-san
        - Shoujo Kageki Revue Starlight
        - Grand Blue
        - Happy Sugar Life
        - Angolmois
        - Satsuriku no Tenshi
        - Jashin\-chan Dropkick
        - Chio\-chan no Tsuugakuro
        - Harukana Receive
        - Banana Fish
        - Isekai Maou to Shoukan Shoujo no Dorei Majutsu
        - Aru Zombie Shoujo no Sainan
        - Planet With
        - Asobi Asobase
        - Hataraku Saibou
        - Island
        - Hanebado
        - High School DxD Hero
        - Isekai Izakaya \- Koto Aitheria no Izakaya Nobu
        - Wotaku ni Koi wa Muzukashii
        - Highschool DxD Hero
        - Steins Gate 0
        - Golden Kamuy
        - Amanchu! Advance
        - Persona 5 The Animation
        - Sword Art Online Alternative
        - Hinamatsuri
        - Mahou Shoujo Site
        - Lostorage Conflated WIXOSS
        - Comic Girls
        - Megalo Box
        - Tada\-kun wa Koi wo Shinai
        - Tokyo Ghoul re
        - Uma Musume
        - Beatless
        - Dagashi Kashi S2
        - Darling in the FranXX
        - Takunomi
        - Overlord II
        - Ryuuou no Oshigoto!
        - Mitsuboshi Colors
        - Gakuen Babysitters
        - Ramen Daisuki Koizumi-san
        - Itsudatte Bokura no Koi wa 10 cm Datta.
        - Sora yori mo Tooi Basho
        - Inuyashiki
        - Imouto sae Ireba Ii
        - Himouto! Umaru\-chan R
        - Wake Up, Girls
        - Kekkai Sensen
        - Houseki no Kuni
        - Mahoutsukai no Yome
        - Blend S
        - Two Car
        - Love Live
        - Yuki Yuna wa Yusha de Aru
        - Shoujo Shuumatsu Ryokou
        - Net\-juu no Susume
        - Konohana Kitan
        - Just Because!
        - Juuni Taisen
        - Osake wa Fuufu ni Natte Kara
        - Shingeki no Bahamut
        - Hajimete no Gal
        - Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu
        - Tenshi no \3P!
        - Princess Principal
        - Centaur no Nayami
        - Ballroom e Youkoso
        - Made in Abyss
        - Isekai Shokudou
        - Aho Girl
        - DanMachi Gaiden
        - Zero kara Hajimeru Mahou no Sho
        - Shuumatsu Nani Shitemasuka Isogashii Desuka Sukutte Moratte ii Desuka
        - Eromanga-sensei
        - Hinako Note
        - Twin Angel BREAK
        - Seikaisuru Kado
        - Tsuki ga Kirei
        - Renai Boukun
        - Busou Shoujo Machiavellianism
        - Sakura Quest
        - Rokudenashi Majutsu Koushi to Akashic Records
        - THE IDOLM@STER CINDERELLA GIRLS Theater \(Web\)
        - THE IDOLM@STER CINDERELLA GIRLS Theater \(TV\)
        - Shingeki no Kyojin
        - BanG Dream
        - Chain Chronicle
        - Kono Subarashii Sekai ni Shukufuku wo! 2 
        - Kobayashi-san Chi no Maid Dragon
        - Piace - Watashi no Italian
        - ACCA \- 13\-ku Kansatsu
        - Gabriel DropOut
        - Demi-chan wa Kataritai
        - Urara Meirochou
        - Seiren
        - Youjo Senki
        - Minami Kamakura Koukou
        - Ao no Exorcist
        - Schoolgirl Strikers
        - Akiba's Trip
        - Fate Grand Order
        - All Out
        - 3\-gatsu no Lion
        - Udon no Kuni no Kiniro Kemari
        - Lostorage Incited WIXOSS
        - Watashi ga Motete Dousunda
        - Mahou Shoujo Ikusei Keikaku
        - Nazotokine
        - Hibike! Euphonium
        - Kiitarou Shounen no Youkai Enikki
        - Cheating Craft
        - Zutto Mae Kara Suki Deshita
        - Yuri!!! on ICE
        - Occultic;Nine
        - Sangatsu no Lion
        - Brave Witches
        - Long Riders
        - Stella no Mahou
        - Soushin Shoujo Matoi
        - Flip Flappers
        - Girlish Number
        - Trickster
        - Shakunetsu no Takkyuu Musume
        - Touken Ranbu
        - Okusama ga Seitokaichou
        - Mahou Shoujo Ikusei Keikaku
        - Shuumatsu no Izetta
        - Bloodivores
        - WWW\.Working
        - Active Raid S2
        - \91 Days
        - Alderamin on the Sky
        - Amanchu
        - Taboo Tattoo
        - Regalia
        - Planetarian
        - Kono Bijutsubu
        - Fate Kaleid
        - New Game
        - Arslan
        - Amaama to Inazuma
        - Tales of Zestiria the X
        - Rewrite
        - Shokugeki no Soma
        - Love live
        - ReLIFE
        - Kuromukuro 
        - Show By Rock
        - Big Order 
        - Onigiri 
        - Wagamama High Spec 
        - Macross Delta 
        - Sansha Sanyou 
        - Sakamoto 
        - Flying Witch 
        - Haifuri 
        - Netoge no Yome 
        - Kabaneri
        - Joker Game 
        - Hundred
        - Bakuon
        - Macross Delta
        - Kuma Miko 
        - Pan de Peace
        - Boku no Hero Academia 
        - Re Zero
        - Kiznaiver 
        - Mayoiga 
        - Terra Formars 
        - Jojo's 
        - Space Patrol Luluco 
        - Bubuki Buranki
        - Nurse Witch
        - Kono Subarashii Sekai
        - Akagami no Shirayukihime
        - Dagashi Kashi
        - Ooyasan wa Shishunki!
        - Nijiiro Days
        - Musaigen no Phantom World
        - Shoujo-tachi wa Kouya wo Mezasu
        - Active Raid
        - One-Punch Man
        - Yuru Yuri
        - Digimon Adventure tri
        - Working
      720p:
        - Action Heroine Cheer Fruits
        - Frame Arms Girl
        - Kuzu no Honkai
        - Urara
    download:
      path: ~/torrents
      overwrite: yes
      

  fff:
    rss: https://nyaa.si/?page=rss&u=FFF
    series:
      flac:
        - selector spread
        - Love Lab
        - Shokugeki no Souma
        - Yuusha ni Narenakatta Ore 
        - selector infected
        - Dungeon ni Deai
        - Akatsuki no Yona
        - Gochuumon wa Usagi Desu ka
        - Jinsei
        - Kill la Kill
        - Hibike!
        - Yuru Yuri San Hai
        - Rokka no Yuusha
        - Highschool DxD
      1080p:
        - Kono Subarashii Sekai ni Shukufuku wo!
      720p:
        - Sakura Quest
    download: ~/torrents

  ddy:
    rss: https://nyaa.si/?page=rss&u=DameDesuYo
    series:
      1080p:
        - Flying Witch
      flac:
        - Punch Line
        - Re Zero kara Hajimeru Isekai Seikatsu
        - Working!!!
        - DanMachi
      720p:
        - Re Zero kara Hajimeru Isekai Seikatsu
    download: ~/torrents
  Asenshi:
    rss: https://nyaa.si/?page=rss&u=Asenshi
    series:
        - Yama no Susume:
            season_packs: always
        - Violet Evergarden
        - Yuru Camp
        - Hisone to Masotan
    download: ~/torrents
